import { FiAlertCircle, FiCheckCircle, FiDollarSign, FiShoppingCart } from 'react-icons/fi'
import { Link } from 'react-router-dom'

import { formatCurrency, formatOrderDate } from '../../utils/orderFormatters.js'
import ReportSummary from './ReportSummary.jsx'

function PurchaseReport({ summary = {}, rows = [] }) {
  const supplierRows = summary.supplierWise || []
  return <div className="space-y-5">
    <ReportSummary items={[
      { label: 'Total Purchase', value: formatCurrency(summary.totalPurchaseAmount), icon: FiShoppingCart },
      { label: 'Paid Amount', value: formatCurrency(summary.paidAmount), icon: FiCheckCircle, color: 'bg-emerald-50 text-emerald-700' },
      { label: 'Due Amount', value: formatCurrency(summary.dueAmount), icon: FiAlertCircle, color: 'bg-amber-50 text-amber-700' },
      { label: 'Total Purchases', value: summary.totalPurchases || 0, icon: FiDollarSign, color: 'bg-blue-50 text-blue-700' },
    ]} />
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm shadow-slate-200/40"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold text-slate-900">Supplier-wise Purchases</h2><p className="mt-0.5 text-xs text-slate-500">Purchase totals grouped by supplier</p></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Supplier</th><th className="px-4 py-3 text-center">Purchases</th><th className="px-4 py-3 text-right">Total Amount</th><th className="px-4 py-3 text-right">Paid Amount</th><th className="px-5 py-3 text-right">Due Amount</th></tr></thead><tbody className="divide-y divide-slate-100">{supplierRows.map((supplier) => <tr key={supplier.supplierId || supplier.supplierName} className="text-slate-700"><td className="px-5 py-3.5">{supplier.supplierId ? <Link to={`/suppliers/${supplier.supplierId}`} className="record-link" title="View supplier details">{supplier.supplierName}</Link> : supplier.supplierName}</td><td className="px-4 py-3.5 text-center">{supplier.totalPurchases}</td><td className="px-4 py-3.5 text-right font-medium">{formatCurrency(supplier.totalPurchaseAmount)}</td><td className="px-4 py-3.5 text-right text-emerald-700">{formatCurrency(supplier.paidAmount)}</td><td className="px-5 py-3.5 text-right text-amber-700">{formatCurrency(supplier.dueAmount)}</td></tr>)}{!supplierRows.length && <tr><td colSpan="5" className="px-5 py-10 text-center text-slate-500">No supplier totals match the selected filters.</td></tr>}</tbody></table></div></section>
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm shadow-slate-200/40"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold text-slate-900">Purchase Details</h2><p className="mt-0.5 text-xs text-slate-500">Purchases matching the selected filters</p></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Purchase No.</th><th className="px-4 py-3">Date</th><th className="px-4 py-3">Supplier</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Total</th><th className="px-4 py-3 text-right">Paid</th><th className="px-5 py-3 text-right">Due</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((purchase) => <tr key={purchase._id || purchase.purchaseNo} className="text-slate-700"><td className="px-5 py-3.5">{purchase._id ? <Link to={`/purchases/${purchase._id}`} className="record-link" title="View purchase details">{purchase.purchaseNo}</Link> : purchase.purchaseNo}</td><td className="px-4 py-3.5">{formatOrderDate(purchase.purchaseDate)}</td><td className="px-4 py-3.5">{purchase.supplierName}</td><td className="px-4 py-3.5"><span className="font-medium">{purchase.purchaseStatus}</span><span className="block text-xs text-slate-500">{purchase.paymentStatus}</span></td><td className="px-4 py-3.5 text-right">{formatCurrency(purchase.finalAmount)}</td><td className="px-4 py-3.5 text-right text-emerald-700">{formatCurrency(purchase.paidAmount)}</td><td className="px-5 py-3.5 text-right text-amber-700">{formatCurrency(purchase.dueAmount)}</td></tr>)}{!rows.length && <tr><td colSpan="7" className="px-5 py-10 text-center text-slate-500">No purchases match the selected filters.</td></tr>}</tbody></table></div></section>
  </div>
}

export default PurchaseReport
